### ISSUE TITLE
Generate Case-classes for Avro Specific API

### ISSUE THREAD

**Issue by vidma** [julianpeeters/avrohugger#1]
- what's the status of this? did you get any closer, have any hints or met some obstacles?
- If that was relatively simple, I may try to implement the `extending of SpecificRecordBase` - our current use-case would be reading/writing Parquet-Avro in Scalding (it works fine generating the quite nasty Java-like SpecificRecord classes, but case-classes would be much nicer)

**Comment by vidma** [comment]
OK, I see https://github.com/julianpeeters/avro-scala-macro-annotations is one of the options. will check how well does it behave with Parquet-Avro in Scalding...

**Comment by julianpeeters** [comment]
I've got some tests left to do, and will publish this week. Glad you're trying the annotations.

**Comment by julianpeeters** [comment]
released 0.0.2 with support for Specific
