### ISSUE TITLE
Scavro java.time vs joda.time for timestamp

### ISSUE THREAD

**Issue by hsn10** [julianpeeters/avrohugger#100]
When compiling to scavro support classes java.time is used as type for _timestamp-millis_. Scavro depends on code generated by avro schema to java compiler as well, but this compiller is using joda.time for dealing with dates. Patch for avro to compile using java.time is in Jira, but avro is not actively maintained at this time.

**Comment by julianpeeters** [comment]
dropped support for Scavro
