### ISSUE TITLE
Make union types usable with SpecificRecordBase

### ISSUE THREAD

**Issue by FloWi** [julianpeeters/avrohugger#103]
We need our model classes to inherit from SpecificRecordBase for serialization. It’d be great if we could make it possible to render union-types other than union {null, Foo}. 

We thought it’d be possible to introduce an intermediate sealed trait (e.g. RecordName+fieldname) and make the records referenced in the union inherit from that. But I’m not sure if that makes sense. We could enable that be creating a new union-setting for the generator. 

Do the java-libs support union types? Maybe we can learn from their logic. 

It’s a pity that you can’t reference protocols in avro. 

I think I have time for implementing that next week. So it’d be great if you could point me in the right direction on how to implement that. 

We’ll discuss this on Tuesday, but maybe you already have an idea in mind on how to implement that. 

Regards, Florian

**Comment by julianpeeters** [comment]
Thanks for your interest, @FloWi! I'm not interested in supporting any of the many semi-arbitrary strategies to try to derive a name avro's unnamed unions when represented in Scala. Unions are coming in Scala 3.0, and until then,  I'll only be accepting PRs for representing them as Shapeless Coproducts. (like was done for `Standard` format [here](https://github.com/julianpeeters/avrohugger/pull/77), [here](https://github.com/julianpeeters/avrohugger/pull/76), [here](https://github.com/julianpeeters/sbt-avrohugger/pull/45), and [here](https://github.com/julianpeeters/sbt-avrohugger/pull/46)). This feature would be on my back burner, likely a timeframe of several weeks.


If you feel that I'm overlooking a representation that should be considered, please provide runnable PRs, or examples of the avsc or avdl and the scala you'd like to generate.

**Comment by FloWi** [comment]
Hi @julianpeeters! Thanks for your response. I appreciate that you took the time to write a good explanation why that feature doesn't make sense. At least not before scala 3 comes along. We decided to not use avro for our message-exchange (since we serialize to json anyway).
