### ISSUE TITLE
Sealed trait hierarchy from a union of avsc contract references

### ISSUE THREAD

**Issue by z4f1r0v** [julianpeeters/avrohugger#110]
Hello,

I would like to know if there is a way to define a union of my avro contracts in `.avsc` files such that I get a sealed trait hierarchy. Currently if I define three or more separate contracts in different files and have another one that references them as separate values of "types", I get a case class with an HLIst of all the types I have listed. Can I override this behaviour?

**Comment by julianpeeters** [comment]
Sorry @alexanderzafirov that's not supported, and it's unlikely to be supported in the future. Currently only represented as Option, Either, or Shapeless Coproduct. Better support for unions in Scala will come in Scala 3.0, and avrohugger will prioritize support for that them before. Support for sealed trait unions may require ensuring that relevant classes get generated into the right files so that the traits could be sealed? There are also complications around generating that trait's name, since avro itself doesn't have named unions.

**Comment by TomasMikula** [comment]
Hi! It would be useful to generate a sealed hierarchy of _wrappers_ for a union type. (Maybe that's what @alexanderzafirov meant?)

The complication with generating the name for the trait remains, but I believe could be resolved in some way, such as using the field's name if the union is a type of a field.

For example, the type of the field `foo` in

```
{
  "type": "record",
  "name": "MyRecord",
  "fields": [
    {
      "name": "foo",
      "type": ["Bar", "Baz", "Qux", "string"]
    }
  ]
}
```

could be generated as

```scala
sealed trait Foo
object Foo {
  case class CaseBar(value: Bar) extends Foo
  case class CaseBaz(value: Baz) extends Foo
  case class CaseQux(value: Qux) extends Foo
  case class CaseString(value: String) extends Foo
}
```

Compared to Shapeless Coproduct, this
 - results in nicer pattern matching;
 - does not require dependency on Shapeless;
 - is less wrapping: The amount of wrapping here is 1 for each case, whereas with Shapeless Coproduct it is proportional to the position of each case (the `String` case would be wrapped 4 times: `Inr(Inr(Inr(Inl("hi"))))`).

**Comment by julianpeeters** [comment]
Hello @TomasMikula ! 

Thanks very much for the details. However I'm still strongly opposed. I'd agree that both suggestions here would be nice, but there doesn't seem to be a viable strategy for generating the trait without breaking avro's spec and generating a lot of pitfalls for avrohugger's users and maintainers. (E.g., a strategy using type names introduces a chance for conflict between fields in the same scope, as well as new constraints on schema evolution). So to support this I think the first step would be to add support for named unions in to apache avro itself.

Alternatively, with Scala 3 coming down the pike, there is a plan to support true Scala unions, in case that'd be an improvement for you. Not sure of a time frame on that, however.

**Comment by julianpeeters** [comment]
@TomasMikula sounds like you might already be familiar, but I forgot to mention `fold` as an alternative to pattern matching with shapeless coproducts https://stackoverflow.com/questions/34107849/pattern-matching-with-shapeless-coproduct

**Comment by TomasMikula** [comment]
Thanks for your reply!

> a strategy using type names introduces a chance for conflict between fields in the same scope

A more complete output of my example schema above would be

```scala
case class MyRecord(foo: MyRecord.Foo)
object MyRecord {
sealed trait Foo
  object Foo {
    case class CaseBar(value: Bar) extends Foo
    case class CaseBaz(value: Baz) extends Foo
    case class CaseQux(value: Qux) extends Foo
    case class CaseString(value: String) extends Foo
  }
}
```

That is, the generated type `Foo` would be inside `object MyRecord`. So there is no possibility of conflict with a field named `foo` of, say `AnotherRecord`.

> as well as new constraints on schema evolution

Could you please elaborate?

> Alternatively, with Scala 3 coming down the pike, there is a plan to support true Scala unions, in case that'd be an improvement for you. Not sure of a time frame on that, however.

I think the release of Scala 3 and subsequent migration of the Scala ecosystem to Scala 3 is still years away.

> I forgot to mention `fold` as an alternative to pattern matching with shapeless coproducts

Thanks for pointing that out. However, defining a `shapeless.Poly1` function seems like a lot of accidental complexity.
