### ISSUE TITLE
Target temp direcotry created for Scavro and SpecificRecord is SBT / Maven specific

### ISSUE THREAD

**Issue by zladovan** [julianpeeters/avrohugger#117]
When `Scavro` or `SpecificRecord` format is used there are temporary files created under **target** directory. Target directory could be good choice when you are using SBT or Maven. 

But when you use avrohugger from Gradle the equivalent directory is called **build** so additional directory (target) is created under project root. 

> In Gradle there is concept of [Gradle daemon](https://docs.gradle.org/current/userguide/gradle_daemon.html) which causing not deleting target directory and temp files remains in project. This is because JVM is not stopped after build (runs still in background) and `file.deleteOnExit` is not applied.

It would be nice if `target` directory would be **replaced by system's temp directory** (`java.io.tmpdir` property).

> I have created [gradle-avrohugger-plugin](https://github.com/zladovan/gradle-avrohugger-plugin) which brings avrohugger to Gradle and for now I need to do some workaround to solve this issue.

**Comment by julianpeeters** [comment]
Thanks for the heads-up @zladovan , I'll try to make this change, this weekend or next.

**Comment by julianpeeters** [comment]
Thanks again @zladovan , avrohugger 1.0.0-RC16 is out, now using the system's temp directory.
