### ISSUE TITLE
Support recursive types

### ISSUE THREAD

**Issue by ppearcy** [julianpeeters/avrohugger#15]
Right now there is a stackoverflow on recursive types. One example that causes this is:
https://svn.apache.org/repos/asf/avro/trunk/share/schemas/org/apache/avro/data/Json.avsc

I have a local fix, but need to do some more work on it.

**Comment by julianpeeters** [comment]
I'd like to support this, but unfortunately this is on my back burner. Much thanks for reporting this though, example and all, and when I have some more time I'll bug you for your scraps.
