### ISSUE TITLE
Plans for non RC release

### ISSUE THREAD

**Issue by jaapterwoerds** [julianpeeters/avrohugger#151]
Hi @julianpeeters ,

First of all thanks for the amazing library. I have been using it in several projects over the last years.

I was wondering what is the strategy for releases. I noticed we're on RC-24 now, does this mean a release is eminent soon? If not, is there any help you can use from the community to get to a 1.0 release?

**Comment by julianpeeters** [comment]
Hi @jaapterwoerds, sorry to leave ya hangin. We're back on semver, avrohugger 1.0.0 and sbt-avrohugger 2.0.0 now available

**Comment by jaapterwoerds** [comment]
Thanks for coming back on this @julianpeeters and for the work you've done on avrohugger 👏
