### ISSUE TITLE
Upgrade Avro version

### ISSUE THREAD

**Issue by joan38** [julianpeeters/avrohugger#154]
Hi,

Would it be possible to upgrade Avro to `1.11.0`?
I'm seeing some critical vulnerabilities on this version:
<img width="1565" alt="Screen Shot 2022-01-25 at 09 41 13" src="https://user-images.githubusercontent.com/1200478/151030035-85d8dd8f-4bcc-40c9-8a41-6503c15092e0.png">

Thanks

**Comment by julianpeeters** [comment]
Thanks for the heads-up, avrohugger is now depending on Avro `1.11.0`, available in version `1.0.0-RC29`.
Awesome to see mill-avro.

**Comment by joan38** [comment]
Perfect thanks!
