### ISSUE TITLE
GenericRecord -> Enumeration doesn't use .Value

### ISSUE THREAD

**Issue by mariussoutier** [julianpeeters/avrohugger#16]
Generating classes using the generic task, it seems Enumerations, when referenced in other classes, lack the `.Value` notation so the classes do not compile.

**Comment by julianpeeters** [comment]
Rats. I'll have some time this weekend to take a look.

**Comment by mariussoutier** [comment]
Thanks!

**Comment by julianpeeters** [comment]
Ok, this should be fixed in avrohugger 0.5.0, sbt-avrohugger 0.2.3, synching with Maven Central in a bit, just to brighten our `Weekday.Monday`.

**Comment by mariussoutier** [comment]
Nice thanks. Hope you didn't have to invest too much time into it.

**Comment by julianpeeters** [comment]
Nah, it was easy. I thought I'd written that test already but I must have pulled one of these: ![Yard Sale](http://ak-hdl.buzzfed.com/static/2014-10/24/15/enhanced/webdr09/enhanced-buzz-13609-1414177859-4.jpg) :) Thanks for reporting.

What took way too much time was a web-app version of avrohugger I've started on, If you ever need a quick and dirty way to get Scala specific records you can check it out here: [avro2caseclass](https://avro2caseclass.herokuapp.com/)(it's on a hobby account, so probably give it a sec to warm up).

Always looking for feedback if you see anything obvious. Like, I used Mongo and Salat, but all the examples are very dated now. Mongo is so easy on Heroku and I don't need performance, but I wonder  what people are using if they don't want to fire up Slick.

Cheers

**Comment by mariussoutier** [comment]
LOL!

The web app is nice, did you design the Avro logo yourself? I'll check the code out and send some PRs :)

**Comment by julianpeeters** [comment]
Hehe. Thanks! The logo is just a black version of the blue one that Avro uses (I figure if they're using it, then using a dead company's name AND logo is weird, but legal...?). And wow, thanks already for the improvements.
