### ISSUE TITLE
Compilation fails for reserved keyword unit

### ISSUE THREAD

**Issue by Edefritz** [julianpeeters/avrohugger#163]
Hi and thanks so much for providing this library!

My team has been using avrohugger for a long time on several projects, but recently we stumbled upon an AVRO schema (which is out of our control), that uses "unit" as a property.

Avrohugger fails to compile the schema to a case class with this error message.

```
[error]  found   : Unit (in scala) 
[error]  required: Unit (in {my_namespace}) 
[error]     ()
[error]     ^
[info] Unit <: {my_namespace}?
[info] false
[error] four errors found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 3 s, completed 17 Jan 2023, 20:14:08
```

It seems that our property clashes with the Scala Unit type. 

I think already figured out that unit seems to be missing in the [set of reserved keywords](https://github.com/julianpeeters/avrohugger/blob/1b44f65dc77ea9d76a20d8ee3a5335d8db48635c/avrohugger-core/src/main/scala/format/FieldRenamer.scala#L6) that are escaped using backticks and I'd be happy to provide a pull-request later.

**Comment by julianpeeters** [comment]
Hi @Edefritz , if it's still relevant, ismailBennamer [may have provided a fix](https://github.com/julianpeeters/avrohugger/pull/169) for your issue in this last release: avrohugger 1.4.0 and sbt-avrohugger-2.4.0

if not, feel free to reopen whenever
