### ISSUE TITLE
AvroGenerateSpecific can generate a schema$ val with length beyond JVM constant limit

### ISSUE THREAD

**Issue by natefitzgerald** [julianpeeters/avrohugger#167]
My organization has a bad habit of using really big Avro schemas. What we found happens is that when AvroGenerateSpecific is used to generate specific records, the `val` that is added to the companion class ends up beyond the ~65k character length limit for compile-time constant strings, the length of which is encoded as a `u2` unsigned int, see [here](https://docs.oracle.com/javase/specs/jvms/se7/html/jvms-4.html#jvms-4.4.7) . I can't link the schema here but it's about 100k characters. 

``` (avro_schemas/compile:compileIncremental) java.lang.IllegalArgumentException: Maximum String literal length exceeded```

I have a somewhat janky solution that I'm planning to PR to this repo but just in case I don't get around to it this is an issue.

**Comment by julianpeeters** [comment]
Ok great, thank you for the report

**Comment by julianpeeters** [comment]
https://github.com/julianpeeters/avrohugger/pull/182
