### ISSUE TITLE
ERROR: Not an Avro data file

### ISSUE THREAD

**Issue by devinbost** [julianpeeters/avrohugger#174]
I think this issue that I created on the downstream repo might actually need to be fixed in this repo. 
https://github.com/makubi/avrohugger-maven-plugin/issues/86

I included details and reproduction steps there.

**Comment by devinbost** [comment]
Was this fixed with a particular commit or PR?

**Comment by julianpeeters** [comment]
Commented here: https://github.com/makubi/avrohugger-maven-plugin/issues/86#issuecomment-1610575282

feel free to reopen, if that doesn't do the trick
