### ISSUE TITLE
Union with null and multiple types does not generate a valid avro class with Either and Option

### ISSUE THREAD

**Issue by ShaneKilloran** [julianpeeters/avrohugger#175]
When trying to generate classes for a schema including a union like: [null, type1, type2], the resulting case class handles it with an Option of an Either, but trying to actually produce with this structure causes an "org.apache.avro.AvroRuntimeException: Unknown datum type scala.util.Left" as only the Option is unwrapped. Is this expected?

**Comment by julianpeeters** [comment]
That's not expected, no. Thanks for the report.

I see a [round trip test](https://github.com/julianpeeters/sbt-avrohugger/blob/0d864f21cb03a4e20f18af7034f261f5fc2c6d0e/src/sbt-test/avrohugger/GenericSerializationTests/src/test/scala/test/standard/StandardUnionsArbitraryAritySpec.scala#L25) for the `Standard` format, but not for `Specific`.

No ETA on a closer look, I'm afraid. This will be on my radar, but I no timeframe.

**Comment by julianpeeters** [comment]
fixed in avrohugger 1.5.4 https://github.com/julianpeeters/avrohugger/pull/178
