### ISSUE TITLE
Ability to add mixins to generated case classes

### ISSUE THREAD

**Issue by ppearcy** [julianpeeters/avrohugger#19]
I've been playing around with adding this and think it would be a nice to have. I have a simple first pass implementation that adds a list of traits to all records. This makes it possible for the case classes to honor other interfaces enabling generic handling at a more specific type than SpecificRecordBase. 

What I really want though, is the ability to target a specific set of records with certain traits. Not quite sure the best approach, perhaps by namespace or filenames/locations. 

I can share the current code if anyone is interested, opened this ticket to see if others had interest.

**Comment by julianpeeters** [comment]
I'm interested. Death to boilerplate. 

Regarding targeting specific sets of records, I'm unsure of the best approach as well. However it seems that by record name, by namespace, and by file would cover a broad range of specificity, while  being a fairly natural set of just 3 settings, presumably easy to maintain. Are you using Avrohugger directly or via the sbt plugin? Perhaps you could share a gist of your proposed API, with a few comments about what you like and dislike about it?

**Comment by ppearcy** [comment]
Hi Julian,
  I've been thinking about this the wrong way. A perfect solution already exists in scala via type classes, something like this:
http://alvinalexander.com/scala/scala-how-to-add-new-methods-to-existing-classes

Thanks again for the great libs. Closing...

**Comment by julianpeeters** [comment]
Ah cool thanks for sharing
