### ISSUE TITLE
Revisit default values for empty constructor

### ISSUE THREAD

**Issue by mariussoutier** [julianpeeters/avrohugger#20]
Hi,

the required empty constructor initializes values to "non-empty" values, i.e. Option with Some, List with one element, Int to 1, Long to 1L, and so on. Could we change this to empty values, None, Nil, 0, 0L, ...?

Cheers
- Marius

**Comment by mariussoutier** [comment]
Ok I just realized that default values are checked, cool.

**Comment by mariussoutier** [comment]
Default values can fix most, but not all defaults. `array<string> items = null;` will generate an empty List, but now Avro isn't happy: `[WARNING] Avro: Invalid default for field contexts: null not a {"type":"array","items":"string"}`.

**Comment by julianpeeters** [comment]
Hey Marius,

I'm happy to make the change, I expect tonight. 

If I recall, default values are well tested, so I wonder why it's failing for a null array, maybe I only tested non-null cases? I'll take a look this weekend.

**Comment by mariussoutier** [comment]
The null array was just an oversight on my part, the empty array is `[]` and that works as expected.

**Comment by julianpeeters** [comment]
Oh good news, thanks for the tip. I'll see what I can do about cleaning up the base defaults.

**Comment by mariussoutier** [comment]
Thanks!

**Comment by julianpeeters** [comment]
New base defaults: https://github.com/julianpeeters/avrohugger/blob/master/avrohugger-core/src/main/scala/format/specific/matchers/DefaultParamMatcher.scala#L20

avrohugger 0.6.1 and sb-avrohugger 0.5.1 should by syncing up with maven central shortly.

Have a nice Friday night!

**Comment by mariussoutier** [comment]
Perfect, thaaaanks!
