### ISSUE TITLE
Generated Scala file imports old Scavro package

### ISSUE THREAD

**Issue by zcox** [julianpeeters/avrohugger#30]
When generating Scavro case classes, the generated Scala file contains:

``` scala
import com.oysterbooks.scavro.{AvroMetadata, AvroReader, AvroSerializeable}
```

This seems to be an outdated Scavro package name, and will not compile with the current Scavro release `"org.oedura" %% "scavro" % "1.0.1"`.

When this is changed to the following, it compiles successfully:

``` scala
import org.oedura.scavro.{AvroMetadata, AvroReader, AvroSerializeable}
```

**Comment by julianpeeters** [comment]
Thanks very much for the heads up. This is expected to be fixed in a contributed patch that adds decimal support, probably about a week away. Sorry for the inconvenience. If this a major inconvenience for you, then let me know and I'll push out an update, and clean up later.

**Comment by zcox** [comment]
One week is totally fine @julianpeeters - we are just starting to evaluate several Scala/Avro tools for use with Kafka and the Confluent Schema Registry - no rush at all. 

The Scavro case classes generated by Avrohugger are really nice! Here's a little example: https://github.com/zcox/scavro-avrohugger-example. Would love to hear any feedback you have on it.

**Comment by julianpeeters** [comment]
That readme is a superb distillation. You all always seem to be working on cool stuff. Looking forward to seeing what you decide on.

I'm glad you're getting some use out of the project; I like how those classes worked out too. I don't mean to get political, but sometimes I wonder if the extra runtime dependency is worth the immutable fields. I mean, are _you_ hiring people that go around mutating variables? I kid, I kid, It's just that I've seen so many Avro-Scala projects languish or perish (for better or worse), that I've even got some sympathies for sticking with Java! I can't resist the benefits of case classes tho, and there are a couple handfuls of companies that seem to have committed to using Scala classes to represent their Avro records, so hopefully one of them would take the reigns of avrohugger if I were hit by a meteor. Anyways, Scavro (and your addition) seems to be as safe and clean as Avro gets if you need models compatible with a SpecificRecord API (tho I wish someone found that package bug sooner :)  ).

**Comment by zcox** [comment]
Thanks for looking at that scavro-avrohugger-example project, your feedback is greatly appreciated. Also thank you for all of the awesome Scala/Avro work you do.

We have seriously considered just writing Avro schemas by hand and using generated Java classes in our Scala code. The simplicity of that approach almost outweighs using mutable Java objects. The allure of immutable Scala case classes is pretty strong though. Will let you know where we land.

**Comment by julianpeeters** [comment]
Hey Zach,

Looks like that decimals patch is delayed indefinitely, but the scavro package name has been updated in avrohugger 0.9.2, sbt-avrohugger 0.9.5.

Talk to you soon,
-Julian

**Comment by zcox** [comment]
Nice! I verified the fix in https://github.com/zcox/scavro-avrohugger-example. Going to close this issue now, thanks for fixing this.

**Comment by julianpeeters** [comment]
Hey @zcox , turns out I was mistaken when I wrote:

> Scavro (and your addition) seems to be as safe and clean as Avro gets if you need models compatible with a SpecificRecord API

Despite relying on SpecificRecord under the hood, I'm not aware of a way to use Scavro records with the Specific API (e.g. as Scalding requires).

I'm definitely still liking Scavro, but I've also been impressed with [avro4s](https://github.com/sksamuel/avro4s), which also offers immutable case classes, but also provides a type class for converting to GenericRecord (making GenericRecord clean enough to use IMO). This makes avro4s records compatible with many systems' Java Avro API (but still not Scalding sadly, AFAIK).

P.S. Thanks again for the lead, btw. Looks like we're getting close now, we'll see what happens.

**Comment by zcox** [comment]
@julianpeeters thanks for pointing out avro4s, haven't evaluated that one yet, will add it to the list. Glad to hear things are getting close. 😄
