### ISSUE TITLE
Giving a field the name "field" causes generated specific record get/set variable shadowing and return of the field index instead of field value

### ISSUE THREAD

**Issue by kyal** [julianpeeters/avrohugger#31]
"field" is a valid name for a record field but it is shadowed by the argument 'field:Int' for getting/setting by field id. Because of the cast to AnyRef the compiler doesn't catch this and you get a ClassCastException of integer to char sequence.

Generated method parameter should be renamed to something illegal in avro or something like "____field".

Example:
avro:
...
  "fields"    : [
    {
      "name"    : "field",
      "type"    : "string" 
    }
]
...

generated specific case class:
case class MyCaseClass(var field: String, ....
def get(field: Int): AnyRef = {
 field match {
      case pos if pos == 0 => {
        field // returning method's argument cast to AnyRef. thankfully this was a String in the record definition and not an Int. imagine the subtle bugs on that one hah!
      }.asInstanceOf[AnyRef]
...

Location of problem: 
 DEF("get", AnyRefClass) withParams(PARAM("field", IntClass)) on line 28 of GetGenerator

**Comment by julianpeeters** [comment]
Yikes! Lucky indeed. Thanks very much for the thorough report. Should be fixed now in Avrohugger version 0.9.3 and sbt-avrohugger version 0.9.6.
