### ISSUE TITLE
Protocols extend Product which fails on Enumerations

### ISSUE THREAD

**Issue by mariussoutier** [julianpeeters/avrohugger#44]
I have this code generated which obviously fails because Enumeration is not a Product.

```
sealed trait TrackingProtocol extends Product with Serializable

final object Source extends Enumeration with TrackingProtocol {
  type Source = Value
  val Frontend, Backend = Value
}
```

**Comment by julianpeeters** [comment]
The quality of the 0.10.X releases were less than stellar. 0.11.0 is nice tho, and it fixed https://github.com/julianpeeters/avrohugger/issues/37. Is that the same as what you're running into?

**Comment by mariussoutier** [comment]
Oops sorry, you're right, I'm still on 0.10 on that particular project. 0.11 working fine, thanks.
