### ISSUE TITLE
Support for Unions with more than two items

### ISSUE THREAD

**Issue by nakulgan** [julianpeeters/avrohugger#50]
Consider the following schema

``` json
 {
         "name":"transformer",
         "type":[
             "null",
             {
                "name":"Transformer",
                "type":"record",
                "fields":[
                    {
                        "name":"builtIn",
                        "type": { "name": "BuiltIn", "type": "enum", "symbols": ["SNOWPLOW_TO_NESTED_JSON"] }
                    }
                ]
             },
             {
                 "name":"JavascriptTransformer",
                 "type":"record",
                 "fields":[
                     {
                         "name":"javascript",
                         "type": "string"
                     }
                 ]
              }
         ]
      }
```

This throws runtime exception **unions not yet supported beyond nullable fields**
from [here](https://github.com/julianpeeters/avrohugger/blob/master/avrohugger-core/src/main/scala/format/specific/converters/ScalaConverter.scala#L97)

The Union in the above schema does have a null. But is violating (>2) number of items in union. However, Avro specs do permit multiple named records in a union.

See discussion here snowplow/kinesis-tee#9

Please advice.

**Comment by JeroenSoeters** [comment]
We would also like to see this feature. I was thinking of serializing this onto a case class hierarchy. So consider the schema

```
 {
         "name":"shape",
         "type":[
             {
                "name":"Circle",
                "type":"record",
                "fields":[
                    {
                        "name":"radius",
                        "type": "long"
                    }
                ]
             },
             {
                 "name":"Rectangle",
                 "type":"record",
                 "fields":[
                     {
                         "name":"width",
                         "type": "long"
                     },
                     {
                         "name":"height",
                         "type": "long"
                     }
                ]
              }
         ]
      }
  }
```

This could be represented as the following case class hierarchy

```
sealed trait Shape
case class Circle(radius: Long) extends Shape
case class Rectangle(width: Long, height: Long) extends Shape
```

I'm thinking the only way to name the trait is the field name that contains the union type. Then there can be a special case when the union type just represents a nullable.

**Comment by shutej** [comment]
There looks to see some substantive discussion in:

https://github.com/snowplow/kinesis-tee/issues/9#issuecomment-256247943

...is this on the roadmap at this point?

**Comment by julianpeeters** [comment]
@shutej yes, some prototypes are about to be implemented. Hard to estimate an ETA however, perhaps there will be an update on this in a few weeks/months timeframe.
