### ISSUE TITLE
Explicitly referenced types from other namespaces inside UNION types aren't imported

### ISSUE THREAD

**Issue by mcoffin** [julianpeeters/avrohugger#56]
[`getRecordSchemas`](https://github.com/julianpeeters/avrohugger/blob/master/avrohugger-core/src/main/scala/format/abstractions/Importer.scala#L82) fails to account for the possible presence of types from another namespace mentioned inside `UNION` types, meaning that those types will never be imported at the end of the day.

**Comment by julianpeeters** [comment]
Thanks for drilling into this. I'm happy to merge a PR if you're working on a fix, otherwise I expect ~1-2 weeks for me (tho I hope sooner).

**Comment by mcoffin** [comment]
I'm working on a PR but my fix doesn't quite work, I'll investigate and *hopefully* finish it up tonight.
