### ISSUE TITLE
Can you provide an example of read/write avro file in HDFS by code generation with avrohugger?

### ISSUE THREAD

**Issue by ChenShuai1981** [julianpeeters/avrohugger#58]
Can you provide an example of read/write avro file in HDFS by code generation with avrohugger? Thanks!

**Comment by julianpeeters** [comment]
Sorry @ChenShuai1981, I'm afraid I won't have the time for quite a while. Perhaps if you provided me a minimal runnable example of what you would like see, but reading/writing regular text, then I could find the time to convert it to Avro with code generation.
