### ISSUE TITLE
Update to avro 1.8.1

### ISSUE THREAD

**Issue by Khrol** [julianpeeters/avrohugger#59]
Avro 1.8.1 was released quite some time ago.
Is it possible to update the plugin?
https://github.com/julianpeeters/avrohugger/blob/master/project/Build.scala#L7

**Comment by julianpeeters** [comment]
Yes, but it's non-trivial: https://issues.apache.org/jira/browse/AVRO/fixforversion/12333322/?selectedTab=com.atlassian.jira.jira-projects-plugin:version-summary-panel

Hoping to have time this Spring or Summer, PRs welcome

**Comment by julianpeeters** [comment]
update: in avrohugger 1.0.0-RC8 the avro schema parser that avrohugger uses has been updated to avro version 1.8.2 (in order to support decimal logical types), available to all formats. However, SpecificRecords are still only generated on par with avro 1.7.7 (e.g. missing 1.8 features such as UUID)
