### ISSUE TITLE
Output avro enum as Scala String

### ISSUE THREAD

**Issue by jon-morra-zefr** [julianpeeters/avrohugger#71]
Spark does not have a native representation of enums.  This makes using avrohugger with Spark very difficult when the avro type has enums in it.  The easiest way around this is to add the ability for avrohugger to read in enum types from the avro schema and generate these types as String.  While I recognize this is not an accurate mapping of the supplied type, this will make loading typed data into Spark a LOT easier.

**Comment by julianpeeters** [comment]
Yeah, that makes sense. `avroScalaCustomEnumStyle` could have a setting like `("enum" -> "string")`. Unless somebody beats me to it, I'll have a better idea of my timeframe in about a month or so.

**Comment by ryan-deak-zefr** [comment]
@julianpeeters I'll take this on today.  Hopefully I can have a PR by the end of the long weekend.

**Comment by ryan-deak-zefr** [comment]
@julianpeeters:  I didn't have a chance to take this on.  In the interest of time, I decided to rewrite enums in avro files as string-based variables and use *avrohugger*, unmodified, to emit the Scala data types.  Do you think that you'll be able to take a look at this in a month or so as indicated above?

**Comment by julianpeeters** [comment]
@ryan-deak-zefr no prob at all. Yes, that's looking like the right time frame for me.

**Comment by johnnycaol** [comment]
This makes sense, and would be nice to have. spark-avro also maps enum to string https://github.com/databricks/spark-avro This change will make this library a lot more useful for spark users.

**Comment by ryan-deak-zefr** [comment]
Agreed.  We are spark users and do some conditional SBT stuff to get around this.  I wanted to do it directly in avrohugger but I had trouble finding the time.

**Comment by julianpeeters** [comment]
Howdy Gang,

**Comment by julianpeeters** [comment]
Howdy Gang,

I finally found some time to implement this and add some thorough tests. If you'd like to kick the tires, please try avrohugger version 1.0.0-RC2 or sbt-avrohugger 2.0.0-RC2. Here's an [example](https://github.com/julianpeeters/sbt-avrohugger/blob/master/src/sbt-test/avrohugger/GenericStringEnumSerializationTests/build.sbt#L5) of how it is used.
