### ISSUE TITLE
External Schema Imports via AVSC Schema

### ISSUE THREAD

**Issue by htimur** [julianpeeters/avrohugger#74]
There is currently a problem with code generation for the schemas with nested enum types in `avsc` schema, for example if you have the same enum definition in 2 schemas then the case class generation gives an error, as the case object/enumeration already exists for one of the cases. 

As it's described in [AVRO-1188](https://issues.apache.org/jira/browse/AVRO-1188), there should be a possibility to specify the external imports for the `avsc` schema, to separate the definitions. 

Or the generation should ignore classes which already exist.

What do you think? And how feasible is it to implement?

**Comment by julianpeeters** [comment]
Hi @htimur, sorry for the long delay. If this still interests you, I believe you are right: it would not cause any harm, and in fact would be very nice, if the generation ignored classes which already exist.

This is feasible to implement: avrohugger has a `SchemaStore` that can be queried with a schema before the avro SchemaParser chokes on it. Now that I think about it, the `SchemaParser` itself might be able to be queried. In either case, we'd have to keep namespace re-mapping in mind and check the custom namespace map, but it seems entirely doable. Unfortunately my timeframe is uncertain, likely on a "months" scale.

**Comment by julianpeeters** [comment]
I believe this is fixed in avrohugger version 1.0.0-RC4 and sbt-avrohugger 2.0.0-RC4
