### ISSUE TITLE
Standard format should not generate Java enums that depend on apache avro

### ISSUE THREAD

**Issue by julianpeeters** [julianpeeters/avrohugger#81]
example: https://github.com/julianpeeters/avrohugger/blob/master/avrohugger-core/src/test/expected/standard/other/ns/java/Suit.java

Question: How to write java (treehugger only writes Scala, and avro generates enums compatible with specific records).

Answer:
a) strip avro info from avro generated enum string
b) generate the enum string manually
c) ???

**Comment by mariussoutier** [comment]
I didn't realize that enums are generated via Avro - I thought you'd just write it out using treehugger.

**Comment by julianpeeters** [comment]
Alrighty, a fix should be syncing up with Maven Central shortly, in avrohugger version 1.0.0-RC3 and sbt-avrohugger version 2.0.0-RC3

**Comment by mariussoutier** [comment]
Thank you so much!
