### ISSUE TITLE
Seq should be favored over List for implementing the Avro Array type

### ISSUE THREAD

**Issue by chrisalbright** [julianpeeters/avrohugger#90]
It seems to me that the types in use should be as general as possible, so as to allow for any implementation to be used for a field. As "List" is an implementation of "Seq", "Seq" should be the type  used (or at least be available for use) for the Avro Array. The Avro compiler for Java in fact doesn't use a specific Collection implementation for the Avro Array, but uses the List interface, leaving it open.

I got here because I've run into a problem with Apache Spark trying to deserialize data in Parquet files into classes generated using Avrohugger (using the avrohugger-maven-plugin). Parquet is in fact using Seq to encode Avro Arrays and is trying to assign to List in the Avrohugger-generated case classes.

Here is the error:

> org.apache.spark.sql.AnalysisException: cannot resolve '[list of spark types...]' due to data type $ ismatch: argument 1 requires scala.collection.immutable.List type, however, '[list of spark types...]' is of scala.collection.Seq type.; at org.apache.spark.sql.catalyst.analysis.package$AnalysisErrorAt.failAnalysis(package.scala:42)

Just by way of verification, I re-proved to myself that Seq accepts it's own derivatives, but not vice-versa. (I realize this example is pedantic; that is not my intention - but instead to just share some of my thought process in coming to this.)

Seq allows any Seq derivative
```
@ val seq0: Seq[Int] = Seq(1)
seq0: Seq[Int] = List(1)

@ val seq1: Seq[Int] = List(1)
seq1: Seq[Int] = List(1)

@ val seq2: Seq[Int] = Array(1)
seq2: Seq[Int] = WrappedArray(1)

@ val seq3: Seq[Int] = Vector(1)
seq3: Seq[Int] = Vector(1)
```

Subtypes do not allow assignment of more general types
```
@ val vector0: Vector[Int] = Seq(1)
cmd4.sc:1: type mismatch;
 found   : Seq[Int]
 required: Vector[Int]
val vector0: Vector[Int] = Seq(1)
                              ^
Compilation Failed

@ val vector1: Vector[Int] = Vector(1)
vector1: Vector[Int] = Vector(1)

@ val array0: Array[Int] = Seq(1)
cmd4.sc:1: type mismatch;
 found   : Seq[Int]
 required: Array[Int]
val array0: Array[Int] = Seq(1)
                            ^
Compilation Failed

@ val array1: Array[Int] = Array(1)
array1: Array[Int] = Array(1)

@ val list0: List[Int] = Seq(1)
cmd4.sc:1: type mismatch;
 found   : Seq[Int]
 required: List[Int]
val list0: List[Int] = Seq(1)
           
                ^
Compilation Failed

@ val list1: List[Int] = List(1)
list1: List[Int] = List(1)
```

**Comment by julianpeeters** [comment]
Good idea, and thanks for all the notes. I can't be sure of a time frame, but I'll look Seq on the todo list.
