### ISSUE TITLE
Union Ordering and Defaults issue

### ISSUE THREAD

**Issue by bellemare** [julianpeeters/avrohugger#99]
Currently using avrohugger and sbt-avrohugger for the following workflow:

1) Convert multiple avsc files to scala case classes (ie: A, B, C)
2) Creating a new wrapper case class, holding a reference for each object from 1: (ie: WrapperClass(a: A, b:B, c:C)
3) Serialize the object from 2, write to disk.

The problem I have is that a number of the union orderings do not appear to be respected. For instance, in A I have:
```
{
      "name": "sort_order",
      "type": [
        "int",
        "null"
      ],
      "default": 0
    }
```
but when I output the merged tuple, I end up with this field as:

```{
      "name": "sort_order",
      "type": [
        "null",
        "int"
      ],
      "default": 0
    },
```

This gives me a warning when trying to re-consume this data downstream:
```[WARNING] Avro: Invalid default for field sort_order: 0 not a ["null","int"]```

Is there a setting that I am missing to enforce the correct ordering as according to the Avro standard? I would not expect the ordering of the union to change.

My build.sbt file for the project includes the following snippet to run avrohugger during compile:

```
avroScalaCustomTypes in Compile := {
  avrohugger.format.Standard.defaultTypes.copy(
    enum = avrohugger.types.JavaEnum)
}

sourceGenerators in Compile += (avroScalaGenerate in Compile).taskValue

(avroScalaSource in Compile) := new java.io.File(sourceManaged.value, "main")

```

If this is a bug, please let me know, otherwise perhaps I could include an addition to the documentation so that others may be able to debug this issue on their own.

Thanks

**Comment by julianpeeters** [comment]
Hi @bellemare, avrohugger does the codegen only, so the expectation is that the class that's generated has the right types and right default values.

Just guessing, but if you see a strange schema upon de/serialization, then presumably the library that you're using to serializing with is generating a schema from the class, behind the scenes, and not respecting the default value. If you can pass the serialization library a schema instead, you can get one by using the following to generate one with the case class, in it's companion object. 
avroScalaCustomTypes in Compile := {
  avrohugger.format.Standard.defaultTypes.copy(
    enum = avrohugger.types.JavaEnum,
    record = ScalaCaseClassWithSchema)
}

hope this helps

**Comment by bellemare** [comment]
Ahhhh yup! My bad. I was confused as to which part was doing what. This is not an avrohugger issue.
